language: go
go:
  - "1.14.7"
services:
  - postgresql
env:
  global:
    - BAKULAN_DB_USER=postgres
    - BAKULAN_DB_PASSWORD=postgres
    - BAKULAN_DB_HOST=localhost
    - BAKULAN_DB_NAME=bakulan
    - BAKULAN_DB_PORT=5432
before_script:
  - psql -c 'create database bakulan;' -U postgres
script:
  - scripts/cibuild
sudo: false
