#!/usr/bin/env bash
# Usage: scripts/gocover
#
# Coverage test

set -e
go test
go test ./api/user/... -covermode=count -coverprofile=cover.out
go test ./api/user/... -json > test-report.out
go test ./api/user/... -coverprofile=coverage.out

go test ./api/store/... -covermode=count -coverprofile=cover.out
go test ./api/store/... -json > test-report.out
go test ./api/store/... -coverprofile=coverage.out

go tool cover -func=cover.out
$GOPATH/bin/goveralls -coverprofile=cover.out -service=travis-ci